---
- hosts: all
  vars:
    wildcard_domain: "apps.cloud.chx"
    lb_fqdn: "ocp.cloud.chx"
  tasks:

  - import_tasks: rhev-auth.yml

  - name: Create HAProxy VM for OCP
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: lb
      comment: This is the lb for the OCP cluster
      state: running
      cluster: Default
      template: rhel-7.6-template
      memory: 4GiB
      memory_max: 8GiB
      memory_guaranteed: 2GiB
      cpu_threads: 2
      cpu_cores: 1
      cpu_sockets: 1
      type: server
      operating_system: rhel_7x64
      nics:
      - name: nic1
        profile_name: ovirtmgmt
      wait: true
 
  - name: Create VMs for OpenShift
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ item }}"
      comment: This is {{ item }} for the OCP cluster
      state: running
      cluster: Default
      template: rhel-7.6-template
      memory: 12GiB
      memory_max: 24GiB
      memory_guaranteed: 8GiB
      cpu_threads: 2
      cpu_cores: 2
      cpu_sockets: 1
      type: server
      operating_system: rhel_7x64
      nics:
      - name: nic1
        profile_name: ovirtmgmt
      wait: true
    with_items:
      - master1
      - master2
      - master3
      - infra1
      - infra2
      - infra3
      - app1
      - app2
      - app3
  
  - name:  Attach additional disk to VMs for containers
    ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: "{{ item }}_disk2"
      vm_name: "{{ item }}"
      state: attached
      size: 100GiB
      storage_domain: vmdata
      format: cow
      interface: virtio_scsi
      wait: true
    with_items:
      - app1
      - app2
      - app3
      - master1
      - master2
      - master3
      - infra1
      - infra2
      - infra3
  
  - name:  Attach OCS disk to VM 
    ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: "{{ item }}_disk3"
      vm_name: "{{ item }}"
      state: attached
      size: 250GiB
      storage_domain: vmdata
      format: cow
      interface: virtio_scsi
      wait: true
    with_items:
      - app1
      - app2
      - app3

  - name: Obtain VM information
    ovirt_vm_facts:
      auth: "{{ ovirt_auth }}"
      pattern: name=master* or name=infra* or name=app* and cluster=Default
      fetch_nested: true
      nested_attributes: ips

  - name: Write out a viable hosts file for OCP installation
    template:
      src: ../templates/generated_inventory.j2
      dest: ../output_files/generated_inventory.ini

  - name: Obtain Master1 VM information
    ovirt_vm_facts:
      auth: "{{ ovirt_auth }}"
      pattern: name=master1 and cluster=Default
      fetch_nested: true
      nested_attributes: ips

  - name: Set Master1 VM Fact
    set_fact:
      ocp_master: "{{ ovirt_vms.0.fqdn }}"

  - name: Add "{{ ocp_master }}" to in memory inventory
    add_host:
      name: "{{ ocp_master }}"

  - name: Copy inventory to "{{ ocp_master }}"
    copy:
      src: ../output_files/generated_inventory.ini
      dest: /root/generated_inventory.ini
    delegate_to: "{{ ocp_master }}"

  - import_tasks: prep-hosts.yml
##
##
